# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:

# Build stage =================================================================

- stage: Build
  displayName: Build all solutions
  
  jobs:
  - job: Agent Job 1
    displayName: Build Tasks
    pool:
      vmImage: 'windows-latest'
      name: Azure Pipelines
      
    steps:
    
    - task: UseDotNet@2
      displayName: 'Use .Net Core sdk 3.x'
      inputs:
        version: 3.x

    - task: DotNetCoreCLI@2
      displayName: 'Restore Toolbox'
      inputs:
        command: restore
        projects: Src/Dev/Toolbox.Core/Toolbox.Core.sln

    - task: DotNetCoreCLI@2
      displayName: 'Build Toolbox'
      inputs:
        projects: Src/Dev/Toolbox.Core/Toolbox.Core.sln
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Restore MessageNet'
      inputs:
        command: restore
        projects: Src/Dev/MessageNet/MessageNet.sln

    - task: DotNetCoreCLI@2
      displayName: 'Build MessageNet'
      inputs:
        projects: Src/Dev/MessageNet/MessageNet.sln
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: Src/Dev/Toolbox.Core/Toolbox.Core.sln
        arguments: '--configuration $(BuildConfiguration) --filter Category!=LocalOnly'
        testRunTitle: 'Toolbox.Core Tests'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True
      enabled: false

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      enabled: false
      condition: succeededOrFailed()


